chatapp/urls.py
from django.urls import path
from .chat_consumers import ChatConsumer
from . import views

app_name='chatapp'


urlpatterns = [
    
    path("", views.index, name="index"),
    path('direct',views.DirectMessage.as_view(),name='messages'),
    path("<str:room_name>", views.room, name="room"),

]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chatapp.urls')),
    path('posts/', include('posts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chatapp/models.py
from django.db import models
from django.conf import settings
# Create your models here.

User=settings.AUTH_USER_MODEL



class Room(models.Model):
    name=models.CharField(max_length=150,null=True,blank=True)
    first_user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='sender')
    second_user=models.ForeignKey(User,on_delete=models.CASCADE,related_name='reciever')
    create_time=models.DateTimeField(auto_now_add=True)
    uid=models.CharField(max_length=150,null=True,blank=True)


    def __str__(self):
        return f"{self.name}"

class Message(models.Model):
    room=models.ForeignKey(Room,on_delete=models.CASCADE,null=True,blank=True)
    sender = models.ForeignKey(User,on_delete=models.CASCADE)
    content = models.TextField()
    timestamp=models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.content

chatapp/views.py
from django.shortcuts import render
from .models import Room,Message
from django.conf import settings
from django.views.generic import ListView
from django.contrib.auth import get_user_model  # Import the user model class
from django.db.models import Q


# Create your views here.

User=get_user_model()

def index(request):
    return render(request, "chatapp/index.html")


def room(request, room_name):
    room_named=int(room_name)
    uid=room_named
    second_username=User.objects.get(pk=room_named)
    if Room.objects.get(uid=uid) :
            roomi=Room.objects.get(uid=uid)
            message=Message.objects.filter(room=roomi)
            print(message)
            return render(request, "chatapp/room.html", {"room_name": uid,
                                                         "request_user": request.user,
                                                         "message":message,
                                                         'roomi':roomi,
                                                         'second_username' : second_username
                                                         })

    
    else :
        room_created=Room.objects.create(name=room_name,first_user=request.user,second_user=second_username,uid=room_name)
        
        return render(request, "chatapp/room.html", {"room_name": room_created,
                                                     "request_user": request.user,
                                                     "message":message})

def room_page(request):
    rooms=Room.objects.all()
    users=User.objects.all()
    
    context = {
        'rooms': rooms,
        'users': users
    }
    return render(request,'chatapp/admins.html',context)

class DirectMessage(ListView):
    
    def get(self,request):
        requested_user = User.objects.get(pk=request.user.pk)
        
        related_room = Room.objects.filter (Q(first_user=requested_user) | Q(second_user=requested_user))
        
        context = {
            'request_user' : requested_user,
            'room' : related_room
        }
        
        return render(request,'chatapp/room_list.html',context)

chatapp/templates/chatapp/chatroom.html
<!-- templates/chat/chat.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Real-Time Chat</title>
    <!-- Include CSS and JavaScript libraries -->
</head>
<body>
    <h1>Welcome to the Chat Room</h1>
    <div id="chat-messages">
        <!-- Messages will be displayed here -->
    </div>
    <form id="message-form">
        <input type="text" id="message-input" autocomplete="off">
        <button type="submit">Send</button>
    </form>
    <!-- Include JavaScript code for chat functionality -->
</body>
</html>

chatapp/templates/chatapp/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
</body>
</html>

chatapp/templates/chatapp/room.html
<!-- chat/templates/chat/room.html -->

{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        body {
            /* Set the background image */
            background-image: url('{% static "images/whatsapp-chat-background-q3phxtj5zb6q8puy.jpg" %}');
            /* Specify background size */
            background-size: cover; /* Cover the entire background */
            /* Specify background position */
            background-position: center; /* Center the background image */
            /* Specify any additional background properties */
        }

        
        .chat-sender {
            font-size: small;
            color: black;
            font: bold;
        }



        .first_user {
            border: 2px solid #000; /* Border with a width of 2px and color black */
            background-color : lightyellow;
            font-size: large;
            color: black;
            font: bold;
            float:  right;
            clear: right;
        }
        .second_user {
            font-size: large;
            background-color : lightgreen;
            float : left ;
            clear : left ;

        }

        .chat_message_inputt {
            width : 10%  ; 
        }

        #footer {
            position:fixed;
            
         }
         .room_name{
            width:30% ;
            background-color : black ;
            text-align: center ;
            color : white;
         }
         .chat-sequence {
            width: 100%;
            border: 2px solid black; 
            border-bottom: solid;
            height: 20%;
           
         }
         .chat-room {
            height: 820px; /* Adjust as needed */
            padding: 10px;
        }
    </style>
</head>
<body>
    
{% include 'navbar.html' %}
<div class="chat-room" id="chat-room">
    {% for m in message %}
    <div class="chat-sequence"> 
        {% if m.sender == request_user %}
            <div class="first_user">
                <div class="chat-content">
                    {{m.content}}
                </div>
            </div>
        {% else %}
            <div class="second_user">
                <div class="chat-sender">
                    {{m.sender}}:
                </div>
                <div class="chat-content">
                    {{m.content}}
                </div>
            </div>
        {% endif %}
    </div>
    {% endfor %}
</div>



<div style="position: fixed; bottom: 0;">
    <input id="chat-message-input" type="text" size="80">
    <input id="chat-message-submit" type="button" value="Send">
</div>
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);
        console.log(document.getElementById('room-name'))

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            const sender = data.sender
            const message = data.message

            var messageDiv = document.createElement('div');
    
            // Set class attribute for the message div based on sender
            if (sender === "{{request_user}}") {
                messageDiv.classList.add('first_user');
            } else {
                messageDiv.classList.add('second_user');
            }
            
            // Create a div element for the sender
            var senderDiv = document.createElement('div');
            
            // Check if sender exists and add sender content
           
            // Create a div element for the message content
            var contentDiv = document.createElement('div');
            contentDiv.classList.add('chat-content');
            contentDiv.textContent = message;
            
            // Append sender and content divs to the message div
            messageDiv.appendChild(contentDiv);
            
            // Append the message div to the chat log
            document.getElementById('chat-room').appendChild(messageDiv);

        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message,
                'user':"{{request_user}}"
            }));
            messageInputDom.value = '';
        };
        
    </script>
          
      
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

      
</body>

</html>

chatapp/templates/chatapp/room_list.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Messages</title>


    <style>
        body {
            background-color: black;
        }
        .room_messages{
            background-color: black;
            color: red;
        }

        .name{
            text-align: left;
            font-size: xx-large;
            color: white;
        }
        a:visited { /* Visited links */
            color: white; /* Set the color of the text inside <a> tags */
        }
        a:link{
            color : white;
        }

    </style>
</head>
<body>
    

<div class = "name">
    Messages
</div>






{% if requested_user.pk == r.first_user %}


{% for r in room  %}

<div   class="room_messages">
    <a href="{% url 'chatapp:room' room_name=r.uid %}">{{r.second_user}}</a>
</div>
{% endfor %}

{% else %}
<div    class="room_messages">

    <a href="{% url 'chatapp:room' room_name=r.uid %}">{{r.first_user}}</a>
</div>
{% endif %}



</body>
</html>