accounts/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import RegisterView,active_user,LoginView,UserProfileDetailView,UserUpdateView
from django.conf.urls.static import static  
from django.conf import settings

app_name='accounts'

urlpatterns = [
    path('register/',RegisterView.as_view(),name='register'),
    path('login/',LoginView.as_view(),name='login'),
    path('activate/<uidb64>/<token>',active_user.as_view(),name='activate'),
    path('profile/<int:pk>',UserProfileDetailView.as_view(),name='profile'),
    path('update/<pk>',UserUpdateView.as_view(),name='update'),

    # path('profile/<int:pk>',follow_user,name='follow')

    # path('profile/',user_info,name='profile')

]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chatapp.urls')),
    path('posts/', include('posts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser,PermissionsMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone
from django.contrib.auth.hashers import make_password

class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None,**extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
            **extra_fields,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None,**extra_fields):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
            **extra_fields,
        )
        user.is_staff = True
        user.is_active = True
        user.is_superuser=True
        
        user.save(using=self._db)
        return user        
    
class User(AbstractBaseUser,PermissionsMixin):
    username=models.CharField(_('username'),max_length=150,unique=True)
    first_name = models.CharField (_("firstname"),max_length=150,blank=True)
    last_name = models.CharField (_("lastname"),max_length=150,blank=True)
    email=models.EmailField(_("email"),unique=True)
    mobile=models.CharField(_("mobile"),max_length=11,unique=True,blank=True,null=True)
    is_staff=models.BooleanField(_("staff status"),default=False,help_text=_('show that user can login to panel admin or not'))
    is_active=models.BooleanField(_('active'),default=False,help_text=_('show that user can log in to website or not!'))
    date_joined=models.DateTimeField(_("date_joined"),default=timezone.now)
    image=models.ImageField(_('image'),blank=True,upload_to='images/')
    followers = models.ManyToManyField('self',related_name='follow',blank=True,symmetrical=False)
    following = models.ManyToManyField('self', related_name='fellow',blank=True,symmetrical=False)
    
    objects=MyUserManager()
    
    EMAIL_FIELD='email'
    USERNAME_FIELD='email'
    REQUIRED_FIELDS=[]
    
    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s %s" % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)
    
    def get_absolute_url(self):
        return reverse("accounts:update", kwargs={"pk": self.pk})
    

class UserFollowing(models.Model):
    
    
    user_id=models.ForeignKey(User,verbose_name=_("followings"),related_name='f',on_delete=models.CASCADE)
    # following
    
    following_user_id = models.ForeignKey("User",verbose_name=_('followers'),related_name='p',on_delete=models.CASCADE)
    #followers

    created = models.DateTimeField(auto_now_add=True)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm,UsernameField
from django.contrib.auth import authenticate
from .models import User
from django.conf import settings
from django.forms import EmailInput,TextInput,PasswordInput

class LoginForm(forms.Form):

    email = forms.EmailField(required=True,widget=forms.EmailInput(attrs={
                'class': "form-control", 
                'style': 'max-width: 300px;',
                'placeholder': 'Email'
                }))
    password = forms.CharField(required=True, widget=forms.PasswordInput({
        
                'class': "form-control",
                'style': 'max-width: 300px;',
                'placeholder': 'Password'
                }))
  
    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            user = authenticate(username=email, password=password)
            if user is not None:
                cleaned_data['user'] = user
            else:
                raise forms.ValidationError("Invalid email or password.")

        return cleaned_data
        
class RegisterForm(forms.ModelForm):
    
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput)
    password2 = forms.CharField(
        label="Password confirmation", widget=forms.PasswordInput
    )
    
    class Meta:
        model = User
        fields = ("first_name",
                  "last_name",
                  "mobile",
                  "email",
                  'password1',
                  'password2',
                  )
        
    def clean(self):
            cleaned_data = super().clean()
            password1 = cleaned_data.get('password1')
            password2 = cleaned_data.get('password2')
            if password1 != password2:
                self.add_error('password2', forms.ValidationError('کلطه عبور با تکرارش تطابق ندارند', code='invalid'))
            cleaned_data.setdefault('password', password1)
            
            
            email = cleaned_data.get('email')
            user_registered= User.objects.filter(email=email)
            if user_registered.exists():
                self.add_error('email',forms.ValidationError('این ایمیل قبلا ثبت شده است',code='invali_email'))

            return cleaned_data  
    
    def save(self,commit=True):
            user=super().save(commit=False)
            user.set_password(self.cleaned_data['password'])
            if commit:
                user.save()
            return user

accounts/views.py
from email.message import EmailMessage
from django.shortcuts import get_object_or_404, render,redirect,HttpResponse
from django.views.generic import DetailView,View
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth.views import LoginView
from django.contrib.auth import login,authenticate,logout,get_user_model
from django.core.exceptions import ValidationError
from django.core import mail
from django.views.generic import CreateView
from django.urls import reverse,reverse_lazy
from django.template.loader import render_to_string,get_template
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_decode,urlsafe_base64_encode
from django.utils.html import strip_tags
from base64 import urlsafe_b64encode
from .tokens import account_activation_token
from django.conf import settings
from .models import User,UserFollowing
from .forms import LoginForm,RegisterForm
from django.utils.encoding import force_str
from django.contrib.auth.backends import ModelBackend
from chatapp.models import Room

from django.views.generic.edit import UpdateView


User = get_user_model()

class UserUpdateView(UpdateView):
    model = User
    fields = ['mobile','first_name','last_name']
    template_name_suffix = "update_form"

class LoginView(View):
    template_name='login.html'
    form_class = LoginForm
    
    def get(self,request):
        form=self.form_class
        return render(request,'accounts/login.html',{'form':form})
        
    def post(self,request):
        form=self.form_class(request.POST)
        if form.is_valid():
            print('form is valid')
            user=form.cleaned_data.get('user')
            print(user.pk)
            login(request,user)
        else :
            return render(request,'accounts/login.html',{'form':form})
        return redirect('accounts:profile',pk=user.pk)
            

class RegisterView(CreateView):
    form_class = RegisterForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'
    def get(self,request):
        if request.user.is_authenticated:
            return redirect("accounts:login")
        else:
            form=self.form_class
            return render(request,'accounts/signup.html',context={'form':form})
        
    def post(self,request):
        email_from = settings.EMAIL_HOST_USER
        subject="Welcome To Django Twitter"
        form=self.form_class(request.POST)
        print(form.errors)
        if form.is_valid:
            
            
                    new_user=form.save(commit=False)
                    new_user.is_active=False
                    new_user.save()
                    # template=get_template("acc_active_email.html")
                    token=account_activation_token.make_token(new_user)
                    uid = urlsafe_base64_encode(force_bytes(new_user.pk))
                    current_site = get_current_site(request)
                    context={
                    'user': new_user,
                    'domain': current_site.domain,
                    'uid':uid,
                    'token':token,}
                    html_message = render_to_string('accounts/acc_active_email.html', context)     
                    plain_message = strip_tags(html_message)
                    # email= EmailMessage(subject,html_message,email_from,[new_user.email])
                    mail.send_mail(subject,plain_message,email_from,[new_user.email],html_message=html_message)
                    status=200
                    return HttpResponse('check your email for verification check spam folder too')
        else :
            return render(request,'accounts/signup.html',{'form':form},status=status)              
class active_user(View):
    def get (self,request,uidb64,token):
        try :
            uid = force_str(urlsafe_base64_decode(uidb64))
            user=get_user_model().objects.get(pk=uid)
            if user is not None and account_activation_token.check_token(user,token):
                user.is_active=True
                user.save()
                return render(request,'accounts/email_confirm.html')        
        except (TypeError, ValueError, OverflowError, get_user_model().DoesNotExist):
            user=None
            print('its nokey')  
            return HttpResponse('404')
        

class UserProfileDetailView(DetailView):
    model=User
    template_name="accounts/profile.html"
    context_object_name='profile'
    
    def get(self,request,pk):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        # if request.user.pk==int(pk):
        username = get_object_or_404(User, pk=int(pk))
        followers=UserFollowing.objects.filter(following_user_id=int(pk))
        following=UserFollowing.objects.filter(user_id=int(pk))
        related_user=UserFollowing.objects.select_related('user_id').all()
        # print(User.objects.select_related('following_user_id').all())
        # retrieved=User.objects.get(email=followers.following_user_id)
        # print(userretrieve)
        context ={
                'user':username,
                'request_user':request.user,
                'following':following,
                'followers':followers,
                'related':related_user
                # 'retrieved':retrieved
                
                
            }
        return render(request,template_name='accounts/profile.html',context=context)
        # else : 
        #     return HttpResponse('you are not allow to see here :)')
        
    def post (self,request,pk):
        follower=request.user
        print(follower)
        following=User.objects.get(pk=pk)
        print(following)
        if UserFollowing.objects.filter(user_id=follower,following_user_id=following).exists():
            UserFollowing.objects.get(user_id=follower,following_user_id=following).delete()
            return redirect(to="accounts:profile",pk=pk)

        else :
            new=UserFollowing.objects.create(user_id=follower,following_user_id=following)
            new.save()
            context={
                'new':new
            }
            
            return redirect(to="accounts:profile",pk=pk)

def unfollow_user(request,pk):
    if request.method=='POST':
        follower=request.user
        following=User.objects.get(pk=pk)
        new=UserFollowing.objects.create(user_id=follower,following_user_id=following)
        new.save()

accounts/templates/accounts/Login.html
<form action="{% url 'accounts:login' %}" method="POST">
    {% csrf_token %}

    {{form}}
    <input type="submit">
</form>

accounts/templates/accounts/acc_active_email.html
<p>Hi {{ user.first_name }},</p>

<p>Thanks for signing up. To activate your account, click the link below:</p>

<p><a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}">Activate now</a></p>

<p>Thanks,</p>

<p>Your Team</p>

accounts/templates/accounts/email_confirm.html
<p>your email has been activated</p>

accounts/templates/accounts/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />




    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Login</title>
  </head>

  <form action='{% url 'accounts:login' %}' method="POST">
    {% csrf_token %}


    {% for f in form  %}
    <div>
    {{f.name}} :
    {{f}}
    {% endfor %}
    </div>
    <div class="mb-3 form-check">
      <input type="checkbox" class="form-check-input" id="exampleCheck1">
      <label class="form-check-label" for="exampleCheck1">Check me out</label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>

accounts/templates/accounts/profile.html
{% load static %}

<head>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/blueimp-md5/2.18.0/js/md5.min.js"></script>

    <script src="{% static 'javascript/myscript.js' %}"></script>

</head>

<body>

{% include 'navbar.html' %}
    

<div class="container text-center">



    <div class="row">
        <div class="col-10">
            <p>Username:</p>
            {{user}}
        </div>
        <div class="col">
            {% if user.image %}
        <img src="{{user.image.url}}" class="img-fluid"
                      style="width: 180px; border-radius: 100px;">
        {% endif %}

        </div>

    </div>
   
<br>

<div class="row">
    <div class="col-5">

        <button id= 'open-message' type="button" class="btn btn-outline-primary">Message</button>

    </div>
    <div class="col-5">

        {% if followers.exists  %}

        <form action="{% url 'accounts:profile' user.pk %}" method="post">
            {% csrf_token %}
            <button type="button" class="btn btn-outline-primary">Unfollow</button>
            <input type="submit" value="unfollow">

        </form>
        
        {% else %}
        
        <form action="{% url 'accounts:profile' user.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" value="follow">
            <button type="button" class="btn btn-outline-primary">Follow</button>
        
        </form>
        {% endif %}
    </div>
    

</div>


<div class="row">
    <div class="col-5">
        <p>Followers</p>
        {% for f in followers  %}
        {{f.user_id}}
        {% endfor %}

    </div>
    <div class="col-5">

        <p>Following</p>
        {% for f in following  %}
            {{f.following_user_id}}
        {% endfor %}
    
    </div>

    <P>POSTS:</P>
</div>

<script>

    var userPK = "{{ user.pk }}";
    var request_user="{{request_user.pk}}";


    document.querySelector('#open-message').onclick = function(e) {

        console.log(userPK)
        console.log(request_user)
        if (userPK > request_user) {
           var roomName= '/chat/' + userPK + '/' + request_user
        }
        else {
            var roomName =  '/chat/' + request_user + '/' + userPK ;
        }
        window.location.pathname = roomName;
    };
</script>
</div>


</body>

accounts/templates/accounts/signup.html
<form action="" method="POST">
  {% csrf_token %}

    {{form}}
    <input type="submit" name="" id="">
</form>

accounts/templates/accounts/userupdate_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>