posts/urls.py
from django.urls import path
from posts import views

app_name = 'posts'

urlpatterns = [
    path('post_create/', views.PostCreateView.as_view(), name='post_create'),
    path('post_list/', views.PostListView.as_view(), name='post_list'),
    path('post_detail/<int:pk>/', views.PostDetailView.as_view(), name='post_detail'),
    path('post_update/<int:pk>/', views.PostUpdateView.as_view(), name='post_update'),
    path('add_comment/<int:pk>/', views.AddCommentView.as_view(), name='add_comment'),
    path('add_reaction/<int:pk>/', views.AddReactionView.as_view(), name='add_reaction'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('select2/', include('django_select2.urls')),
    path('accounts/', include('accounts.urls')),
    path('chat/', include('chatapp.urls')),
    path('posts/', include('posts.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from accounts.models import User
from django.utils.translation import gettext_lazy as _
from django.db.models import Count


# Create your models here.
class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = "D", _("Draft")
        PUBLISHED = "P", _("Published")

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    title = models.CharField(verbose_name=_("title"), max_length=255)
    user = models.ForeignKey(
        "accounts.User", on_delete=models.CASCADE, related_name="posts"
    )
    content = models.TextField(verbose_name=_("content"), blank=True)
    status = models.CharField(
        verbose_name=_("status"),
        max_length=1,
        choices=Status.choices,
        default=Status.PUBLISHED,
    )
    tags = models.ManyToManyField("Tag", related_name="posts", blank=True)
    archived = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def count_reactions(self):
        likes = self.reaction_set.filter(liked=True).count()
        dislikes = self.reaction_set.filter(disliked=True).count()
        return likes, dislikes

    def __str__(self):
        return f"{self.title} - {self.user}"


class Reaction(models.Model):
    user = models.ForeignKey(User, verbose_name=_("user"), on_delete=models.CASCADE)
    related_post = models.ForeignKey(
        Post, verbose_name=_("Post"), on_delete=models.CASCADE
    )
    liked = models.BooleanField(default=False)
    disliked = models.BooleanField(default=False)


class Comment(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")
    content = models.TextField()
    reply_to = models.ForeignKey(
        "self", null=True, blank=True, on_delete=models.CASCADE, related_name="replies"
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content


class Image(models.Model):
    post = models.ForeignKey(
        "Post", verbose_name=_("post"), on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to="post/image/")
    is_featured = models.BooleanField(verbose_name=_("is featured"), default=False)
    alt = models.CharField(verbose_name=_("alternative"), max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-is_featured", "-created_at"]


class Tag(models.Model):
    name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class PostTagFollow(models.Model):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    tag = models.ForeignKey("Tag", on_delete=models.CASCADE)

posts/forms.py
from django import forms
from .models import Post, Image, Comment, Reaction, Tag
from django.forms import inlineformset_factory
from django_select2 import forms as select2_forms


class TagSelect2Widget(select2_forms.ModelSelect2MultipleWidget):
    search_fields = [
        "name__icontains",
    ]
    queryset = Tag.objects.all()


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content", "reply_to"]


class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ["image", "alt", "is_featured"]

    def __init__(self, *args, **kwargs):
        super(ImageForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({"class": "form-control"})


class PostForm(forms.ModelForm):
    new_tag = forms.CharField(label="New Tag", required=False)

    class Meta:
        model = Post
        fields = ["title", "content", "status", "tags", "archived"]
        widgets = {
            "tags": TagSelect2Widget,
        }

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs.update({"class": "form-control"})

    def clean(self):
        cleaned_data = super().clean()
        new_tag = cleaned_data.get("new_tag")
        if new_tag:
            tag, created = Tag.objects.get_or_create(name=new_tag)
            cleaned_data["tags"] = list(cleaned_data.get("tags", [])) + [tag]
        return cleaned_data


class ReactionForm(forms.ModelForm):
    class Meta:
        model = Reaction
        fields = ["liked", "disliked"]
        widgets = {"liked": forms.HiddenInput(), "disliked": forms.HiddenInput()}


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]


ImageFormSet = inlineformset_factory(
    Post, Image, form=ImageForm, extra=3, can_delete=True
)

posts/views.py
from django.shortcuts import render, redirect
from posts.forms import PostForm, ImageFormSet, CommentForm, ReactionForm
from posts.models import Post, Comment, Reaction
from django.views.generic import CreateView, ListView, DetailView, UpdateView, FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.http import Http404
from django.db.models import Prefetch


# Create your views here.


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_create.html"
    message = "Post created successfully"

    def get_success_url(self):
        return reverse_lazy("posts:post_detail", kwargs={"pk": self.object.pk})

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["image_formset"] = ImageFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["image_formset"] = ImageFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        form.instance.user = self.request.user
        self.object = form.save()
        self.save_images(self.object, self.request.POST, self.request.FILES)
        messages.success(self.request, self.message)
        return super().form_valid(form)

    def save_images(self, post_instance, post_data, files_data):
        image_formset = ImageFormSet(post_data, files_data, instance=post_instance)
        if image_formset.is_valid():
            image_formset.save()


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = "posts/post_list.html"

    def get_queryset(self):
        return (
            Post.objects.filter(archived=False)
            .order_by("-created_at")
            .prefetch_related(Prefetch("comments", to_attr="latest_comments"))
        )

    def get_context_data(self, **kwargs):
        """
        Retrieves the context data for the view.
        Args:
            **kwargs: Additional keyword arguments.
        Returns:
            dict: The context data for the view.
        This method overrides the `get_context_data` method of the parent class.
        It retrieves the context data by calling the parent class method with the provided keyword arguments.
        It sets the 'reaction_form' key in the context data by creating an instance of `ReactionForm`.
        The resulting context data is returned.
        """

        context = super().get_context_data(**kwargs)
        context["reaction_form"] = ReactionForm()
        return context


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    template_name = "posts/post_detail.html"

    def get_context_data(self, **kwargs):
        """
        Retrieves the context data for the view.
        Args:
            **kwargs: Additional keyword arguments.
        Returns:
            dict: The context data for the view.
        This method overrides the `get_context_data` method of the parent class.
        It retrieves the context data by calling the parent class method with the provided keyword arguments.
        It sets the 'comment_form', 'reaction_form', 'reactions', 'comments',
        'tags', 'likes', and 'dislikes' keys in the context data.
        """

        data = super().get_context_data(**kwargs)
        post = self.get_object()
        likes, dislikes = post.count_reactions()
        if post.archived:
            raise Http404("Post does not exist")
        data["comment_form"] = CommentForm()
        data["reaction_form"] = ReactionForm()
        data["reactions"] = get_object_or_404(Post, pk=post.pk)
        data["comments"] = post.comments.all()
        data["tags"] = post.tags.all()
        data["likes"] = likes
        data["dislikes"] = dislikes
        return data


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "posts/post_update.html"

    def get_success_url(self):
        return reverse_lazy("posts:post_detail", kwargs={"pk": self.object.pk})

    def dispatch(self, request, *args, **kwargs):
        """
        Dispatches the request to the appropriate handler method.
        Parameters:
            request: The request object.
            args: Additional positional arguments.
            kwargs: Additional keyword arguments.
        Returns:
            The result of the dispatch method.
        """

        self.object = self.get_object()
        if self.object.user != self.request.user:
            raise Http404("You are not allowed to update this post.")
        return super().dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """
        Retrieves context data for the view based on the provided keyword arguments.
        Sets 'image_formset' in the context data based on the request POST data and files.
        Returns the updated context data.
        """

        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["image_formset"] = ImageFormSet(
                self.request.POST, self.request.FILES, instance=self.object
            )
        else:
            data["image_formset"] = ImageFormSet(instance=self.object)
        return data

    def form_valid(self, form):
        """
        Validates the form and saves the associated post.

        Args:
            form (Form): The form containing the post data.

        Returns:
            HttpResponse: The response object with the redirect URL.

        This method sets the user of the form instance to the current request user,
        saves the form and the associated object, saves any images related to the post,
        and invokes the parent class's form_valid method with the form.
        The result of the parent class's form_valid method is returned.
        """

        form.instance.user = self.request.user
        self.object = form.save()
        self.save_images(form)
        return super().form_valid(form)

    def save_images(self, form):
        """
        Save the images associated with the post.
        Parameters:
            form (Form): The form containing the post data.
        Returns:
            None
        This method retrieves the image formset from the context data and checks if it is valid.
        If it is valid, it sets the instance of the image formset to the current object and saves it.

        """
        context = self.get_context_data()
        image_formset = context["image_formset"]
        if image_formset.is_valid():
            image_formset.instance = self.object
            image_formset.save()


class AddCommentView(LoginRequiredMixin, FormView):
    model = Comment
    form_class = CommentForm
    template_name = "posts/post_detail.html"

    def get_success_url(self):
        next_page = self.request.GET.get("next", None)
        if next_page == "list":
            return reverse_lazy("posts:post_list")
        else:
            post_pk = self.kwargs.get("pk")
            return reverse_lazy("posts:post_detail", kwargs={"pk": post_pk})

    def form_valid(self, form):
        """
        Validates the form and saves the associated comment.
        Args:
            form (CommentForm): The form containing the comment data.
        Returns:
            HttpResponse: The response object with the redirect URL.
        Raises:
            Http404: If the post with the given primary key does not exist.
        """
        post_pk = self.kwargs.get("pk")
        post = get_object_or_404(Post, pk=post_pk)
        form.instance.user = self.request.user
        form.instance.post = post
        form.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        """
        Retrieves the context data by calling the parent class method with the provided keyword arguments.
        Sets 'reply_to_form' in the context by invoking 'get_reply_to_form'.
        Returns the updated context.
        """
        context = super().get_context_data(**kwargs)
        context["reply_to_form"] = self.get_reply_to_form()
        return context

    def post(self, request, *args, **kwargs):
        """
        Handles the POST request. Processes the reply form data if present.
        Redirects to the success URL if the reply form is valid.
        Raises an exception if the reply form is not valid.
        """
        if "reply_to_comment_id" in request.POST:
            reply_to_form = self.get_reply_to_form(request.POST)
            if reply_to_form.is_valid():
                post_pk = self.kwargs.get("pk")
                post = get_object_or_404(Post, pk=post_pk)
                reply_to_form.instance.user = self.request.user
                reply_to_form.instance.post = post
                reply_to_form.save()
                return redirect(self.get_success_url())
            else:
                raise Exception("Reply form is not valid.")

        return super().post(request, *args, **kwargs)

    def get_reply_to_form(self, data=None):
        """
        Generates a reply form for the given data.
        Parameters:
            data (dict, optional): The data to initialize the form with. Defaults to None.
        Returns:
            CommentForm: The reply form without the 'reply_to' field.
        """
        reply_to_form = CommentForm(data)
        del reply_to_form.fields["reply_to"]
        return reply_to_form


class AddReactionView(LoginRequiredMixin, FormView):
    """
    A class-based view that handles adding reactions (likes/dislikes) to posts.
    Requires users to be logged in.
    """

    model = Reaction
    form_class = ReactionForm
    template_name = ["posts/post_detail.html", "posts/post_list.html"]

    def get_success_url(self):

posts/templates/posts/comment_template.html
<li class="list-group-item">
    {{ comment.content }} - {{ comment.user }}
    <button type="button" class="btn btn-link replyBtn" data-bs-toggle="collapse"
            data-bs-target="#replyForm{{ comment.id }}" aria-expanded="false"
            aria-controls="replyForm{{ comment.id }}">Reply to
    </button>
    <div class="collapse" id="replyForm{{ comment.id }}">
        <form method="post" action="{% url 'posts:add_comment' post.id %}?next=list">
            {% csrf_token %}
            <div class="form-group">
                <label for="commentContent{{ comment.id }}">Your Comment</label>
                <textarea class="form-control" id="commentContent{{ comment.id }}" name="content"
                          rows="3"></textarea>
                <input type="hidden" name="reply_to" value="{{ comment.id }}">
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    {% if comment.replies.all %}
        <ul class="list-group mt-2">
            {% for reply in comment.replies.all %}
                {% include 'posts/comment_template.html' with comment=reply %}
            {% endfor %}
        </ul>
    {% endif %}
</li>

posts/templates/posts/post_create.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Post Create</title>
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    {{ form.media.css }}
</head>
<body>
<div class="container mt-5">
    <h1 class="mb-4">Create Post</h1>
    <form method="post" enctype="multipart/form-data" id="post-form">
        {% csrf_token %}
        {% if message %}
            <div class="alert alert-success">
                {{ message }}
            </div>
        {% endif %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.title.label_tag }}
            {{ form.title }}
            {{ form.title.errors }}
        </div>
        <div class="form-group">
            {{ form.content.label_tag }}
            {{ form.content }}
            {{ form.content.errors }}
        </div>
        <div class="form-group">
            {{ form.status.label_tag }}
            {{ form.status }}
            {{ form.status.errors }}
        </div>
        <div class="form-group">
            {{ form.tags.label_tag }}
            {{ form.tags }}
            {{ form.tags.errors }}
        </div>
        <div class="form-group">
            {{ form.new_tag.label_tag }}
            {{ form.new_tag }}
            {{ form.new_tag.errors }}
        </div>
        <div class="form-group">
            {{ form.archived.label_tag }}
            {{ form.archived }}
            {{ form.archived.errors }}
        </div>
        <div id="image-forms" class="hidden">
            {{ image_formset.management_form }}
            {% for form in image_formset %}
                <div class="form-group">
                    {{ form.non_field_errors }}
                    <div class="form-group">
                        {{ form.image.label_tag }}
                        {{ form.image }}
                        {{ form.image.errors }}
                    </div>
                    <div class="form-group">
                        {{ form.alt.label_tag }}
                        {{ form.alt }}
                        {{ form.alt.errors }}
                    </div>
                    <div class="form-group">
                        {{ form.is_featured.label_tag }}
                        {{ form.is_featured }}
                        {{ form.is_featured.errors }}
                    </div>
                </div>
            {% endfor %}
        </div>


        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<!-- Bootstrap JS and dependencies -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
<!-- Custom JS for adding new image forms -->
{{ form.media.js }}
</body>
</html>

posts/templates/posts/post_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Detail</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h1 class="mt-5">Post Detail</h1>
    {% if message %}
        <div class="alert alert-success" role="alert">
            {{ message }}
        </div>
    {% endif %}
    <h2>{{ post.title }}</h2>
    <p>{{ post.content }}</p>

    <h2>Tags</h2>
    <ul class="list-group">
        {% for tag in tags %}
            <li class="list-group-item">{{ tag.name }}</li>
        {% endfor %}
    </ul>

    <h3>Reactions</h3>
    <form action="{% url 'posts:add_reaction' post.id %}" method="post">
        {% csrf_token %}
        {{ reaction_form.as_p }}
        <button type="submit" name="liked" value="True" class="btn btn-primary">Like</button>
        <button type="submit" name="disliked" value="True" class="btn btn-danger">Dislike</button>
        <div class="row">
            <div class="col-md-6">
                <h3>Likes</h3>
                <p>{{ likes }}</p>
            </div>
            <div class="col-md-6">
                <h3>Dislikes</h3>
                <p>{{ dislikes }}</p>
            </div>
        </div>
    </form>
    {% for image in post.images.all %}
        <img src="{{ image.image.url }}" class="img-fluid w-50 mt-3" alt="{{ image.alt }}">
    {% endfor %}

    <!-- Comments -->
    <h3>Comments</h3>
    <ul class="list-group">
        {% for comment in comments %}
            {% if not comment.reply_to %}
                {% include 'posts/comment_template.html' with comment=comment %}
            {% endif %}
        {% endfor %}
    </ul>


    <!-- Comment Form -->
    <div class="mt-3">
        <h3>Leave a Comment</h3>
        <form method="post" action="{% url 'posts:add_comment' post.id %}">
            {% csrf_token %}
            <div class="form-group">
                <label for="commentContent">Your Comment</label>
                <textarea class="form-control" id="commentContent" name="content" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>

    <!-- End Comments -->


    {% if post.user == request.user %}
        <a href="{% url 'posts:post_update' post.id %}" class="btn btn-primary mt-3">Edit Post</a>
    {% endif %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

posts/templates/posts/post_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post List</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <h1 class="mt-5">Post List</h1>
    {% for post in object_list %}
        <div class="card mt-4">
            <div class="card-body">
                <a href="{% url 'posts:post_detail' post.id %}">
                    <h2 class="card-title">{{ post.title }}</h2>
                </a>
                <p class="card-text">{{ post.content }}</p>
                <form action="{% url 'posts:add_reaction' post.id %}?next=list" method="post">
                    {% csrf_token %}
                    {{ reaction_form.as_p }}
                    <button type="submit" name="liked" value="True" class="btn btn-primary">Like</button>
                    <button type="submit" name="disliked" value="True" class="btn btn-danger">Dislike</button>
                </form>
                <div class="row">
                    <div class="col-md-6">
                        <h3>Likes</h3>
                        <p>{{ post.count_reactions.0 }}</p>
                    </div>
                    <div class="col-md-6">
                        <h3>Dislikes</h3>
                        <p>{{ post.count_reactions.1 }}</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-6">
                        <img src="{{ post.images.first.image.url }}" class="img-fluid"
                             alt="{{ post.images.first.alt }}">
                    </div>
                </div>
                <!-- Comments -->
                <h3>Comments</h3>
                <ul class="list-group">
                    {% for comment in post.latest_comments|slice:":3" %}
                        {% if not comment.reply_to %}
                            {% include 'posts/comment_template.html' with comment=comment %}
                        {% endif %}
                    {% endfor %}
                    {% if post.latest_comments|length > 3 %}
                        <li class="list-group-item">
                            <a href="{% url 'posts:post_detail' post.id %}">View all comments</a>
                        </li>
                    {% endif %}
                </ul>


                <!-- Comment Form -->
                <div class="mt-3">
                    <h3>Leave a Comment</h3>
                    <form method="post" action="{% url 'posts:add_comment' post.id %}?next=list">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="commentContent">Your Comment</label>
                            <textarea class="form-control" id="commentContent" name="content" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>

                <!-- End Comments -->
            </div>
        </div>
    {% endfor %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

posts/templates/posts/post_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Post Update</title>
</head>
<body>

<h1>Post Update</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <div id="image-forms">
        {{ image_formset.management_form }}
        {% for form in image_formset %}
            {{ form.as_p }}
        {% endfor %}
    </div>
    <button type="submit">submit</button>
</form>


</body>
</html>